In [1]:
import pandas as pd
d=pd.read_csv("C:\\Users\\laksh\\OneDrive\\Desktop\\E-Commerce Sales Analytics.csv")
df=pd.DataFrame(d)

In [2]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,01-01-2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,01-02-2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,01-03-2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,01-04-2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,01-05-2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,09-05-2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,09-06-2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,09-07-2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,09-08-2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,09-09-2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [3]:
print(df.dtypes)

order_id              int64
order_date              str
customer_id           int64
product_category        str
region                  str
quantity              int64
unit_price          float64
discount            float64
payment_method          str
delivery_days         int64
customer_rating     float64
revenue             float64
dtype: object

In [4]:
df.head(5)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,01-01-2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,01-02-2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,01-03-2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,01-04-2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,01-05-2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [5]:
df.tail(5)

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
4995,14996,09-05-2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,09-06-2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,09-07-2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,09-08-2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,09-09-2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [6]:
df.shape

(5000, 12)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   str
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), str(4)
memory usage: 596.2 KB

In [8]:
df.describe()

,order_id,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
std,1443.520003,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219
min,10001.000000,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000

In [57]:
df.sort_values("customer_rating")

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Year,month,Month_name
4511,14512,2034-05-09,1000,Electronics,North,1,594.11,0.17,COD,6,1.0,594.11,2034,5,May
586,10587,2023-08-10,1046,Clothing,North,7,47.75,0.14,COD,2,1.0,334.25,2023,8,August
2465,12466,2028-10-01,1989,Electronics,South,5,22.84,0.10,Card,3,1.0,114.20,2028,10,October
631,10632,2023-09-24,1998,Clothing,North,4,517.73,0.30,Wallet,6,1.0,2070.92,2023,9,September
633,10634,2023-09-26,1446,Electronics,East,3,218.01,0.31,Wallet,4,1.0,654.03,2023,9,September
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1904,11905,2027-03-20,1490,Clothing,South,5,15.77,0.14,Card,4,5.0,78.85,2027,3,March
3617,13618,2031-11-27,1396,Home,East,2,254.47,0.04,COD,2,5.0,508.94,2031,11,November
4940,14941,2035-07-12,1900,Beauty,West,4,424.78,0.08,COD,3,5.0,1699.12,2035,7,July
2193,12194,2028-01-03,1954,Home,East,3,462.78,0.33,COD,6,5.0,1388.34,2028,1,January
2217,12218,2028-01-27,1223,Beauty,North,2,465.88,0.02,Card,1,5.0,931.76,2028,1,January

In [10]:
df.sort_values("product_category")

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,01-01-2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
2,10003,01-03-2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
7,10008,01-08-2022,1020,Beauty,North,6,265.71,0.13,Card,2,3.7,1387.01
12,10013,1/13/2022,1330,Beauty,South,7,483.41,0.30,COD,6,1.4,2368.71
52,10053,2/22/2022,1875,Beauty,East,1,154.01,0.05,Card,2,2.8,146.31
...,...,...,...,...,...,...,...,...,...,...,...,...
4990,14991,8/31/2035,1012,Home,East,1,265.48,0.32,Card,10,2.9,180.53
4991,14992,09-01-2035,1183,Home,North,2,353.46,0.28,COD,9,4.9,508.98
4992,14993,09-02-2035,1110,Home,North,2,285.82,0.03,Wallet,11,4.9,554.49
4994,14995,09-04-2035,1507,Home,South,6,25.85,0.12,Card,5,3.1,136.49
4999,15000,09-09-2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [11]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [12]:
df.dropna()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,01-01-2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,01-02-2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,01-03-2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,01-04-2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,01-05-2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,09-05-2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,09-06-2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,09-07-2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,09-08-2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,09-09-2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [56]:
df.drop(columns="revenue")

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,Year,month,Month_name
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2022,1,January
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,2022,1,January
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,2022,1,January
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2022,1,January
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,2022,1,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,2035,9,September
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,2035,9,September
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,2035,9,September
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,2035,9,September
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,2035,9,September

In [14]:
df.drop(columns="revenue")

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating
0,10001,01-01-2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7
1,10002,01-02-2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9
2,10003,01-03-2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5
3,10004,01-04-2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6
4,10005,01-05-2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9
...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,09-05-2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3
4996,14997,09-06-2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2
4997,14998,09-07-2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4
4998,14999,09-08-2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8
4999,15000,09-09-2035,1214,Home,East,7,231.58,0.34,COD,5,3.9

In [15]:
df["revenue"]=df["quantity"]*df["unit_price"]

In [16]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,01-01-2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55
1,10002,01-02-2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18
2,10003,01-03-2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84
3,10004,01-04-2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35
4,10005,01-05-2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,09-05-2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,743.48
4996,14997,09-06-2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1661.01
4997,14998,09-07-2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,231.66
4998,14999,09-08-2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,553.64
4999,15000,09-09-2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1621.06

In [17]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,01-01-2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55
1,10002,01-02-2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18
2,10003,01-03-2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84
3,10004,01-04-2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35
4,10005,01-05-2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,09-05-2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,743.48
4996,14997,09-06-2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1661.01
4997,14998,09-07-2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,231.66
4998,14999,09-08-2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,553.64
4999,15000,09-09-2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1621.06

In [20]:
df["order_date"]=pd.to_datetime(df["order_date"],format="mixed")

In [21]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,743.48
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1661.01
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,231.66
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,553.64
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1621.06

In [22]:
df["order_date"].head()

0   2022-01-01
1   2022-01-02
2   2022-01-03
3   2022-01-04
4   2022-01-05
Name: order_date, dtype: datetime64[us]

In [23]:
df["order_date"].head(100)

0    2022-01-01
1    2022-01-02
2    2022-01-03
3    2022-01-04
4    2022-01-05
        ...
95   2022-04-06
96   2022-04-07
97   2022-04-08
98   2022-04-09
99   2022-04-10
Name: order_date, Length: 100, dtype: datetime64[us]

In [25]:
df["Year"] = df["order_date"].dt.year

In [26]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Year
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55,2022
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18,2022
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84,2022
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35,2022
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,743.48,2035
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1661.01,2035
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,231.66,2035
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,553.64,2035
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1621.06,2035

In [38]:
df["Month_name"]=df["order_date"].dt.month_name()

In [39]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Year,month,Month_name
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55,2022,1,January
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18,2022,1,January
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84,2022,1,January
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35,2022,1,January
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35,2022,1,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,743.48,2035,9,September
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1661.01,2035,9,September
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,231.66,2035,9,September
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,553.64,2035,9,September
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1621.06,2035,9,September

In [36]:
df["month"]=df["order_date"].dt.month

In [37]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Year,month
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55,2022,1
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18,2022,1
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84,2022,1
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35,2022,1
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35,2022,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,743.48,2035,9
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1661.01,2035,9
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,231.66,2035,9
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,553.64,2035,9
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1621.06,2035,9

In [40]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Year,month,Month_name
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55,2022,1,January
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18,2022,1,January
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84,2022,1,January
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35,2022,1,January
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35,2022,1,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,743.48,2035,9,September
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1661.01,2035,9,September
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,231.66,2035,9,September
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,553.64,2035,9,September
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1621.06,2035,9,September

In [42]:
total_revenue=df["revenue"].sum()
print(total_revenue)

6240021.96

In [43]:
category_revenue=df.groupby("product_category")["revenue"].sum()
print(category_revenue)

product_category
Beauty          933359.92
Clothing       1887131.50
Electronics    2223312.57
Home           1196217.97
Name: revenue, dtype: float64

In [44]:
product_sales=df.groupby("product_category")["quantity"].sum()
print(product_sales)

product_category
Beauty         2995
Clothing       6171
Electronics    7109
Home           3949
Name: quantity, dtype: int64

In [45]:
monthly_sales=df.groupby("month")["revenue"].sum()
print(monthly_sales)

month
1     527122.69
2     499459.12
3     519296.22
4     487268.36
5     594801.06
6     540767.33
7     536574.72
8     559293.15
9     493188.83
10    496311.72
11    497812.14
12    488126.62
Name: revenue, dtype: float64

In [50]:
top_product=df.groupby("product_category")["revenue"].sum().sort_values(ascending=False).head(10)
print(top_product)

product_category
Electronics    2223312.57
Clothing       1887131.50
Home           1196217.97
Beauty          933359.92
Name: revenue, dtype: float64

In [52]:
top_customer=df.groupby("customer_id")["quantity"].sum().sort_values(ascending=False).head(5)
print(top_customer)

customer_id
1663    63
1957    57
1675    55
1935    51
1276    50
Name: quantity, dtype: int64

In [53]:
top_customer=df.groupby("customer_id")["revenue"].sum().sort_values(ascending=False).head(5)
print(top_customer)

customer_id
1663    22546.44
1955    19218.45
1647    18574.98
1675    18404.11
1836    17489.11
Name: revenue, dtype: float64

In [55]:
region_sales = df.groupby("region")["revenue"].sum().sort_values(ascending=False)
print(region_sales)

region
West     1640762.01
North    1566659.99
South    1517429.39
East     1515170.57
Name: revenue, dtype: float64

In [58]:
apply_function=df["revenue"].apply(lambda x: x+1000)
print(apply_function)

0       3615.55
1       1334.18
2       1933.84
3       3622.35
4       1699.35
         ...
4995    1743.48
4996    2661.01
4997    1231.66
4998    1553.64
4999    2621.06
Name: revenue, Length: 5000, dtype: float64

In [60]:
df["month"]

0       1
1       1
2       1
3       1
4       1
       ..
4995    9
4996    9
4997    9
4998    9
4999    9
Name: month, Length: 5000, dtype: int32

In [62]:
df["total_price"]=df["quantity"]*df["unit_price"]

In [63]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Year,month,Month_name,total_price
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55,2022,1,January,2615.55
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18,2022,1,January,334.18
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84,2022,1,January,933.84
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35,2022,1,January,2622.35
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35,2022,1,January,699.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,743.48,2035,9,September,743.48
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1661.01,2035,9,September,1661.01
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,231.66,2035,9,September,231.66
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,553.64,2035,9,September,553.64
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1621.06,2035,9,September,1621.06

In [65]:
df.drop(columns="total_price",inplace=True)

In [66]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Year,month,Month_name
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55,2022,1,January
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18,2022,1,January
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84,2022,1,January
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35,2022,1,January
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35,2022,1,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,743.48,2035,9,September
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1661.01,2035,9,September
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,231.66,2035,9,September
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,553.64,2035,9,September
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1621.06,2035,9,September

In [67]:
df["cost_price"] = df["unit_price"] * 0.70

In [68]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Year,month,Month_name,cost_price
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55,2022,1,January,261.555
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18,2022,1,January,33.418
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84,2022,1,January,217.896
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35,2022,1,January,367.129
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35,2022,1,January,97.909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,743.48,2035,9,September,260.218
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1661.01,2035,9,September,387.569
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,231.66,2035,9,September,54.054
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,553.64,2035,9,September,96.887
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1621.06,2035,9,September,162.106

In [69]:
df["Expenses"] = df["quantity"] * df["cost_price"]

In [70]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Year,month,Month_name,cost_price,Expenses
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55,2022,1,January,261.555,1830.885
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18,2022,1,January,33.418,233.926
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84,2022,1,January,217.896,653.688
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35,2022,1,January,367.129,1835.645
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35,2022,1,January,97.909,489.545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,743.48,2035,9,September,260.218,520.436
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1661.01,2035,9,September,387.569,1162.707
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,231.66,2035,9,September,54.054,162.162
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,553.64,2035,9,September,96.887,387.548
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1621.06,2035,9,September,162.106,1134.742

In [72]:
df["Profit_Loss"] = df["revenue"] - df["Expenses"]

In [73]:
df

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,Year,month,Month_name,cost_price,Expenses,Profit_Loss
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,2615.55,2022,1,January,261.555,1830.885,784.665
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,334.18,2022,1,January,33.418,233.926,100.254
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,933.84,2022,1,January,217.896,653.688,280.152
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2622.35,2022,1,January,367.129,1835.645,786.705
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,699.35,2022,1,January,97.909,489.545,209.805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2035-09-05,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,743.48,2035,9,September,260.218,520.436,223.044
4996,14997,2035-09-06,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1661.01,2035,9,September,387.569,1162.707,498.303
4997,14998,2035-09-07,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,231.66,2035,9,September,54.054,162.162,69.498
4998,14999,2035-09-08,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,553.64,2035,9,September,96.887,387.548,166.092
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1621.06,2035,9,September,162.106,1134.742,486.318

In [74]:
payment_method_analysis=df["payment_method"].value_counts()
print(payment_method_analysis)

payment_method
Card      2270
COD       1774
Wallet     956
Name: count, dtype: int64

In [75]:
df.to_csv("C:\\Users\\laksh\\OneDrive\\Desktop\\E-Commerce Sales Analytics.csv", index=False)